### ISSUE TITLE
首页的 logo 可以约束下高度

### ISSUE THREAD

**Issue by pupboss** [onevcat/vno-jekyll#1]
不然的话点开新文章，左边的 slide bar 上的 logo 会眨一下眼 :-)

**Comment by ASHESZheng** [comment]
我也遇到这个问题了

**Comment by coderZsq** [comment]
请问如何设置 favicon.ico, 放置在images/favicon.png 不起效果

**Comment by pupboss** [comment]
@ASHESZheng logo 的 img 标签添加 width 和 height 约束即可，作者应该已经添加约束了

@coderZsq 既然代码里这么写了那肯定是这个地方，猜测是本地的缓存，你清空下或者用隐私窗口打开看看
