### ISSUE TITLE
您好，我使用了您的主题

### ISSUE THREAD

**Issue by HarryLee-BJ** [onevcat/vno-jekyll#10]
您好，我使用了前辈的主题。首先非常荣幸能够使用到前辈的主题，感谢前辈的无私奉献。
我的博客地址是 http://qiuqi.li 。  
如果可能的话，我也希望能登上前辈的文章Hello World - Vno 的列表。
另外有个小问题，就是如何使网站首页的title不自动引用_config.yml中的title而另起title呢？
再次感谢

**Comment by onevcat** [comment]
Hihi,

可以直接修改一下 https://github.com/onevcat/vno-jekyll/blob/master/_posts/2016-02-16-hello-world-vno.markdown 这个文件然后给我发个 p-r

title 的话可能只能去 side-panel.html 自己改了。

**Comment by HarryLee-BJ** [comment]
好的！非常感谢
