### ISSUE TITLE
修改demo的md文件以后，重新push报"does not have a valid date in the YAML front matter"错误

### ISSUE THREAD

**Issue by dutchmanxj** [onevcat/vno-jekyll#22]
The page build failed for the `master` branch with the following error:

The file `_posts/2016-02-16-hello-world-vno.markdown` does not have a valid date in the YAML front matter. For more information, see https://help.github.com/articles/page-build-failed-invalid-post-date/.

搜了一下解决方案，在_config.yaml里面添加了exclude: [vendor]，没有用，本地也没有生成vendor文件夹。

**Comment by onevcat** [comment]
你改成什么了？

**Comment by dutchmanxj** [comment]
刚才检查了下，发现date被重置成{}，补上时间就好了
