### ISSUE TITLE
该博客存在xss跳转漏洞

### ISSUE THREAD

**Issue by MemoryOfSnow** [onevcat/vno-jekyll#31]
我利用该框架搭建了博客，然后在上面写了一个漏洞记载的文章，文章中有如下语句(我添加了|||以防止该标签被解析)，
<|||meta name="xxxx" content="1;url=http://www.baidu.com" http-equiv="refresh" />
然后，该语句被解析并跳转到baidu，请onecat修复该漏洞。

**Comment by onevcat** [comment]
Markdown 和 HTML 本身就是可以兼容混编的，你可以尝试一下用 “`” 把这行括起来。

**Comment by MemoryOfSnow** [comment]
哦，谢谢你的解答。
