### ISSUE TITLE
sass的版本可以更新下吗?

### ISSUE THREAD

**Issue by Bluelich** [onevcat/vno-jekyll#4]
提示检测的是缺少sass-3.4.21,
可是我已经有了sass-3.4.22,

**Comment by onevcat** [comment]
这个是 jekyll 那边的依赖，主题是管不了的。

而且不是应该 bundler install 一下然后在 local path 下做么..

**Comment by Bluelich** [comment]
谢谢,问题已经解决了，博客已经搭建完成。

非常抱歉，我对这方面了解的太少，不好意思！
