### ISSUE TITLE
Bulid error caused by  highlighter-style(plain)

### ISSUE THREAD

**Issue by Bluelich** [onevcat/vno-jekyll#5]
Jekyll 3.0以上 不支持 jekyll-paginate,style 改为 'rouge' 就可以了吗?

![image](https://cloud.githubusercontent.com/assets/8563315/15525113/9f54597c-2259-11e6-9a20-e22bc8ee1a77.png)

为什么按照原路径替换的文件  avatar 和bg ,访问就失效了呢?

类似main.js的调用路径现在是/js/main.js  是不是应改成../js/main.js
(现在这个电脑的环境还没配好,所以无法验证.... 囧)

我发现vno-jekyll的目录结构和原版的有些区别,是这个原因吗?
是否可以告知下,修正这个路径错误的方式吗?

**Comment by onevcat** [comment]
我的开发环境和使用的是 Jekyll 3.1.1，没什么问题。可能是您配置哪里不太对？

404 的话尝试一下 `jekyll serve`？虽然是静态页面，但是你还是需要一个服务器来 serve 这些页面。

**Comment by zhenlinyang** [comment]
首先非常感谢 @onevcat 提供了这套精美的模版。

我今天收到了来自 support@github.com 的邮件，貌似也是这个问题。

--------

The page build completed successfully, but returned the following warning:

You are attempting to use the 'plain' highlighter, which is currently unsupported on GitHub Pages. Your site will use 'rouge' for highlighting instead. To suppress this warning, change the 'highlighter' value to 'rouge' in your '_config.yml' and ensure the 'pygments' key is unset. For more information, see https://help.github.com/articles/page-build-failed-config-file-error/#fixing-highlighting-errors.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.

**Comment by onevcat** [comment]
换成了 Rouge 作为默认 highlighter~
