### ISSUE TITLE
遇到 {{}}  的时候解析会有问题

### ISSUE THREAD

**Issue by bawn** [onevcat/vno-jekyll#8]
比如文章要写的是：
```
<view class="contain">
    <view wx:for="{{items}}" wx:key="{{item.id}}">
     <text>{{item.text}}</text>
     <text>{{index}}</text>
    </view>
</view>
```

最终显示出来是这样的
```
<view class="contain">
    <view wx:for="" wx:key="">
     <text></text>
     <text></text>
    </view>
</view>
```

**Comment by onevcat** [comment]
Double curly brace is a reversed syntax of Jekyll's render template. So you may need to add raw attribute to make it render properly for you.

See [this post](http://stackoverflow.com/questions/24102498/escaping-double-curly-braces-inside-a-markdown-code-block-in-jekyll) for more.

**Comment by bawn** [comment]
@onevcat Thanks so fast for the reply
